### ISSUE TITLE
[Question] Validators and epoch clarification

### ISSUE THREAD

**Issue by htafolla** [nearprotocol/stakewars#223]
I wanted ask for clarification around epochs and validators participating in staking to clarify the process and add to the docs.

1. An epoch on betanet is 3 hours?
2. Is it possible to determine if an epoch is at the begging or end?
3. If you show up on the kicked list and unstake and restake in the same epoch and your proposal is accepted will you begin staking again on the next epoch?
4. After how many epochs does the V show up in the logs
5. Do you still receive the V on your node if you are staking with a contract?
6. Once your proposal is accepted do you start staking the next epoch?
7. After your proposal is accepted it looks like you disappear from proposals after a little while when do you show up on "near validators next"?

**Comment by jimmy3dita** [comment]
Hi, thank you for asking here, Will answer below:

1. An epoch on betanet is 3 hours?
Correct, we configured BetaNet to switch epoch every 3 hours instead of the canonical 12 on TestNet/MainNet.
2. Is it possible to determine if an epoch is at the begging or end?
There's a feature request for NEAR RPC that will include this information.
Given that every epoch is 10,000 blocks long, you can in the meantime estimate the age of the current epoch by counting the `num_expected_blocks` at a certain block height, by using a cURL similar to this one: `curl --header "Content-Type: application/json" --request POST --data '{"jsonrpc": "2.0", "method": "validators", "id": "dontcare", "params": ["CV1uzYhWsxvyE9A8b4ZUDVGbTaSP1MjQeScngABPgJj3"]}' https://rpc.betanet.near.org | jq`. Note that the "params" is set to a specific block hash (block number `5662828`).
The [example here](https://gist.github.com/jimmy3dita/5c04dd6c8451a67f3029ee63fe9a388c) shows the first block of an epoch, since the sum of every `num_expected_blocks` is equal to `1`.
3. If you show up on the kicked list and unstake and restake in the same epoch and your proposal is accepted will you begin staking again on the next epoch?
No, your node will be kicked out anyway the next epoch, but will get back in the next one.
4. After how many epochs does the V show up in the logs?
The second epoch after the current one.
5. Do you still receive the V on your node if you are staking with a contract?
Absolutely, the node will see no difference
6. Once your proposal is accepted do you start staking the next epoch?
We have to clarify the state of your staking transaction, and define "accepted":
    1. you send a proposal with a certain stake, and it is pending until the end of the epoch. You should be able to see it in the `.result.current_proposals` portion of the `validators` json above
    2. once the epoch is over, your proposal is evaluated and accepted or not. If it is accepted, your node will be included in the `.result.next_validators` portion in the `validators` json above
    3. once this second epoch is over, your node will become validator and will have the `V/xx` in the logs
7. After your proposal is accepted it looks like you disappear from proposals after a little while when do you show up on "near validators next"?
Correct, once your proposal is accepted, it disappears from the `.result.current_proposals` and your validator moves to `.result.next_validators`

**Comment by bowenwang1996** [comment]
Some clarification:
> An epoch on betanet is 3 hours?

It depends on the block production speed, but normally it is between two and three hours.

> Is it possible to determine if an epoch is at the begging or end?

Yes. The validator rpc https://docs.near.org/docs/interaction/rpc#validators will return the epoch start height and you can compare the current block height to that to see where it is in the current epoch.
