### ISSUE TITLE
[Whack-a-Mole] What is missing in the Stake Wars documentation?

### ISSUE THREAD

**Issue by jimmy3dita** [nearprotocol/stakewars#257]
This is an informal discussion about what's missing in the Stake Wars experience, from your point of view. Knowing this from the inside is not that easy: I easily find docs, I participate in meetings and I spend a lot of time talking with my colleagues.

But you are there alone, outside, and you need to find this stuff by yourself! I would really appreciate your transparent (blunt) feedback on what was more difficult for you to understand about being a validator at NEAR. This information will help me rethink docs and Stake Wars information from scratch, improving your experience, and giving more value to your time.

I will start first:
- separate the Stake Wars goals and high-level activities in the `README.md` from step-by-step tutorials (hint: I'm already working on this)
- have a `troubleshooting.md` file

What are yours?

**Comment by bonsfi** [comment]
After near login it is vital to copy the link provided in any browser in order to authorize login. No need to do it in terminal where you are doing the login.

**Comment by htafolla** [comment]
Here is some general feedback:

1. Need a way to notify validators to reboot / upgrade via SMS, email, blasts and pinned posts.
2. Like Anais has on Telgram we should create a channel for contributors to discuss issues, documentation, and support issues outside of the normal channels Or is it preferred to open issues.
3. @jimmy3dita is already writing an existing validator migration guide which is key
4. We should extend additional NEAR to contributors and power users to take multiple sets so that the network can get up and stay up faster during hard-forks and upgrade. On average when there is an issue it seems that we are only 5-8 seats short.
5. We need a clear communication format on the channel for deadlines, upgrades, issues and what is expected.
6. Better oversight of issues with your validator before it's to late. A little Dapp would be good. I had thought about taking a stab at it.
7. Maybe consider moving the epoch down to 1.5 hours since it takes at present 6-9 hours to get a validator back in the pool. Especially if the rate of change is going to increase moving toward testnet.

I am happy to contribute and help in any way as I know this is a critical piece for the project to move forward. Please let me know of any way I can be of assistance.

**Comment by bowenwang1996** [comment]
@htafolla We have updated nearup to automatically detect network upgrades and update accordingly. I think that is sufficient for most users. For more professional ones we will prepare separate documentation on how to proceed and integrate with their infrastructure.

> Maybe consider moving the epoch down to 1.5 hours since it takes at present 6-9 hours to get a validator back in the pool. Especially if the rate of change is going to increase moving toward testnet.

On the contrary, on testnet an epoch is 12 hours. I am not comfortable with a smaller epoch length as that would decrease the surface of testing.

**Comment by jimmy3dita** [comment]
Work in progress here: https://github.com/nearprotocol/stakewars/tree/new-readme

**Comment by abakuz** [comment]
Suggestions for https://github.com/nearprotocol/stakewars:

- Section 4.5 item 1
  - [ ] its not clear what the author means by **"and you have the key to manage my_validator account"**  
   - [ ] `neardev/betanet` this folder is non existent, maybe you mean `.near/betanet`?

- Section 4.5 item 2
  - [ ] `--wasmFile=initial-contracts/staking-pool/res/staking_pool.wasm` probably full path would be better to avoid confusion

- Section 4.5 item 3
  - [ ] `Initialize staking pool at account c2.nearkat for the owner account ID owner c2.nearkat` bug using staking_pool_account twice instead of master_account.
