### ISSUE TITLE
[BEND][application] Don't publish validator IP addresses

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#27]
**Describe the bug or test**
I really don't like the idea of publishing the validator IP addresses.
This opens up a couple of potential attack vectors, such as e.g. the obvious DDOS.
Ofc it could also be critical to the vitality of the blockchain if a couple of validators are down.

**Proposal**
Have a look at ways to at least disguise the validator node IP addresses:
E.g. use boot nodes like Ethereum.

**Comment by ilblackdragon** [comment]
We do use boot nodes for main TestNets. The IP addresses posted by participants at the genesis block are used as boot nodes.

The IP addresses are always known for validators when they are producing blocks/chunks, even if the nodes use boot nodes to connect to the network. 

For miners in Ethereum it's easier because there is 12 second delay to propagate blocks over the network, that said main miner pools in Ethereum also have known addresses. 

In our case when we are trying to squeeze out the latency of the network, we really need to pipeline and route messages directly to the next validator, hence there is information propagated.
This is similar to Cosmos, Polkadot, EOS and other PoS networks where validators at any moment are  entities known to the network.

**Comment by bowenwang1996** [comment]
Looks like not an issue. Closing.
